CREATE TABLE user (
  id   BIGINT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(50)    NOT NULL DEFAULT '',
  username VARCHAR(50)    NOT NULL DEFAULT '',
  nickname VARCHAR(50)    NOT NULL DEFAULT '',
  password VARCHAR(64)   NOT NULL DEFAULT '',
  email VARCHAR(50)     NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL
);
	